### ISSUE TITLE
Can't get block data

### ISSUE THREAD

**Issue by LeonTing1010** [Conflux-Chain/confura#108]
<img width="1222" alt="Screen Shot 2023-03-18 at 21 33 30" src="https://user-images.githubusercontent.com/1998680/226109435-c9443795-70b7-4ed8-874c-816b33004997.png">

**Comment by wanliqun** [comment]
Sorry, we can not handle this issue due to not enough context information provided. Please elaborate more information.

**Comment by wanliqun** [comment]
Besides, it would be good for you to leverage [`go-conflux-sdk`](https://github.com/Conflux-Chain/go-conflux-sdk) to interact with the RPC service.
