### ISSUE TITLE
TODO: `newPendingTransactions` and `syncing` are not implemented in the fullnode yet.

### ISSUE THREAD

**Issue by waelsy123** [Conflux-Chain/confura#122]
I would like to implement this missing feature: 

// eSpace PubSub notification
// TODO:
// 2. `newPendingTransactions` and `syncing` are not implemented in the fullnode yet.

could you please provide more details on what needs to be done? 

I'm not sure if in general other fullnode send these information so I can retrieve it and provide it by PubSub

**Comment by wanliqun** [comment]
Hi, @waelsy123 Thanks for the interest in contributing to `confura`. 

`[Conflux](https://github.com/Conflux-Chain/conflux-rust)` is EVM-compatible by providing EVM space. For now, `confura` serves PubSub requests by delegating a shared proxy connection to the full node. 

So please file your issue to our `[conflux-rust](https://github.com/Conflux-Chain/conflux-rust)` repo for more details.

**Comment by waelsy123** [comment]
Hi @wanliqun I just created another issue on [conflux-rust](https://github.com/Conflux-Chain/conflux-rust): #[issue 2672](https://github.com/Conflux-Chain/conflux-rust/issues/2672) . let me know please what do you think? and I would be available to implement the feature however I just need some technical guidance / onboarding to achieve the mentioned requirements. :)

**Comment by waelsy123** [comment]
@wanliqun is the pending transactions pool being synced among nodes? Or other modes doesn't see transaction until it's committed?

**Comment by wanliqun** [comment]
@waelsy123 Yes, once a transaction submitted to a node, the transaction would by replicated to other nodes within the same cluster group.
